// Video and audio with FFmpeg: routes, command-line choices (no FFmpeg needed) and real conversions, which run only
// when Filee's FFmpeg is installed (`pwsh build/fetch-engines.ps1 -Only ffmpeg`; CI does not install it). Inputs are
// generated by FFmpeg itself (test pattern + sine tone) and every output is checked with ffprobe.

using System.Diagnostics;
using System.Globalization;
using System.Text.Json;
using Filee.Core.Conversion;
using Filee.Core.Formats;
using Filee.Core.Presets;
using Filee.Engines.Infrastructure;
using Filee.Engines.Media;

namespace Filee.Engines.Tests;

/// <summary>
/// FFmpeg keeps every core busy: its tests run on their own, so timing-sensitive tests of other classes (progress
/// estimates) are not starved meanwhile.
/// </summary>
[CollectionDefinition(nameof(FfmpegCollection), DisableParallelization = true)]
public sealed class FfmpegCollection;

[Collection(nameof(FfmpegCollection))]
public class MediaTests(EngineFixture fx) : IClassFixture<EngineFixture>
{
    private static readonly (string Ffmpeg, string Ffprobe)? Tools = FfmpegConverter.Locate();

    private static void SkipUnlessInstalled() =>
        Assert.SkipUnless(Tools is not null, "FFmpeg is not installed (pwsh build/fetch-engines.ps1 -Only ffmpeg)");

    // ───────────────────────── Routes (no FFmpeg needed) ─────────────────────────

    /// <summary>A planner that treats FFmpeg as installed, so these tests also run where it is not.</summary>
    private RoutePlanner Planner() => fx.Catalog.CreatePlanner(["ffmpeg"]);

    [Theory]
    [InlineData("mp4", "webm")]
    [InlineData("mov", "mp4")]
    [InlineData("mkv", "mp4")]
    [InlineData("avi", "mp4")]
    [InlineData("mp4", "mp4")] // re-encode, e.g. the "MP4 720p" preset
    [InlineData("mp4", "gif")]
    [InlineData("mp4", "mp3")]
    [InlineData("webm", "m4a")]
    [InlineData("wav", "mp3")]
    [InlineData("flac", "mp3")]
    [InlineData("mp3", "mp3")] // re-encode, e.g. "MP3 128k"
    [InlineData("m4a", "wav")]
    [InlineData("amr", "mp3")]
    [InlineData("gif", "mp4")]
    [InlineData("gif", "webm")]
    [InlineData("rm", "mp4")]
    [InlineData("dss", "mp3")]
    public void Media_conversions_take_one_ffmpeg_step(string from, string to)
    {
        var route = Planner().Plan(from, to);
        Assert.NotNull(route);
        var step = Assert.Single(route.Steps);
        Assert.Equal("ffmpeg", step.Converter.Id);
    }

    [Theory]
    [InlineData("mp4", "jpg", "magick")]
    [InlineData("mkv", "webp", "magick")]
    [InlineData("mov", "pdf", "pdfsharp")]
    public void Video_to_images_goes_through_one_still_frame_not_an_animated_gif(string from, string to, string imageEngine)
    {
        var route = Planner().Plan(from, to);
        Assert.NotNull(route);
        Assert.Equal([("ffmpeg", from, "png"), (imageEngine, "png", to)], route.Steps.Select(s => (s.Converter.Id, s.From, s.To)));
    }

    [Fact]
    public void Every_writable_video_and_audio_format_is_a_target()
    {
        // A new format in the catalog must get an encoding (or a documented reason why not) in MediaEncoding.
        Assert.Equal(
            FormatRegistry.Known.Where(f => f.Category == FormatCategory.Video && f.Writable).Select(f => f.Id).Order(),
            MediaEncoding.VideoTargets.Keys.Order());
        Assert.Equal(
            FormatRegistry.Known.Where(f => f.Category == FormatCategory.Audio && f.Writable).Select(f => f.Id).Order(),
            MediaEncoding.AudioTargets.Keys.Order());
    }

    [Fact]
    public void Audio_is_never_turned_into_video_and_ffmpeg_is_unavailable_until_installed()
    {
        var planner = Planner();
        Assert.Null(planner.Plan("mp3", "mp4"));
        Assert.Null(planner.Plan("wav", "gif"));

        var ffmpeg = fx.Converters.Single(c => c.Id == "ffmpeg");
        Assert.Equal(Tools is not null, ffmpeg.GetStatus().IsAvailable);
        if (Tools is null)
            Assert.Equal("engine.reason.not_installed", ffmpeg.GetStatus().ReasonKey);
    }

    // ───────────────────────── Command lines (no FFmpeg needed) ─────────────────────────

    private static readonly VideoStreamInfo Hd = new(1920, 1080, 1, 0, 29.97);

    private static IReadOnlyList<string> Args(string target, MediaOptions? options = null, MediaInfo? info = null) =>
        MediaEncoding.Plan("in.mkv", "out." + target, target, options ?? new MediaOptions(),
            info ?? new MediaInfo(TimeSpan.FromSeconds(10), Hd, new AudioStreamInfo(6, 44100), null), "work").Single().Arguments;

    private static string After(IReadOnlyList<string> args, string option) => args[args.ToList().IndexOf(option) + 1];

    [Fact]
    public void Quality_bitrate_and_size_options_reach_the_encoders()
    {
        var mp4 = Args("mp4", new MediaOptions { Quality = MediaQuality.High, MaxHeight = 720 });
        Assert.Equal("libx264", After(mp4, "-c:v"));
        Assert.Equal("18", After(mp4, "-crf"));
        Assert.Equal("scale=w=-2:h='trunc(min(ih,720)/2)*2'", After(mp4, "-vf"));
        Assert.Equal("+faststart", After(mp4, "-movflags"));
        Assert.Equal("768k", After(mp4, "-b:a")); // 256k per stereo pair × 3 pairs (5.1)
        Assert.Equal("mp4", After(mp4, "-f"));

        var webm = Args("webm", new MediaOptions { Quality = MediaQuality.Small, RemoveAudio = true });
        Assert.Equal(["-b:v", "0", "-crf", "38"], webm.SkipWhile(a => a != "-b:v").Take(4));
        Assert.Contains("-an", webm);
        Assert.DoesNotContain("0:a:0", webm);

        var mp3 = Args("mp3", new MediaOptions { AudioBitrateKbps = 130 });
        Assert.Equal("128k", After(mp3, "-b:a")); // snapped to the MP3 bitrate table
        Assert.DoesNotContain("-q:a", mp3);
        Assert.Equal("2", After(Args("mp3"), "-q:a")); // VBR V2 by default

        Assert.Equal("2", After(Args("wma"), "-ac")); // WMA holds two channels at most
        Assert.Equal("8000", After(Args("amr"), "-ar"));
        Assert.Equal("30000/1001", After(Args("mpg"), "-r"));
        Assert.Equal("448k", After(Args("vob"), "-b:a")); // DVD 5.1
    }

    [Fact]
    public void Dvd_and_dv_frames_are_letterboxed_into_the_nearest_tv_shape()
    {
        // 16:9 source: fills the anamorphic 16:9 NTSC frame.
        Assert.Equal("scale=720:480,pad=720:480:(ow-iw)/2:(oh-ih)/2:black,setdar=16/9", MediaEncoding.DvdOrDvFilter(Hd, pal: false));
        // 4:3 source at PAL.
        Assert.Equal("scale=720:576,pad=720:576:(ow-iw)/2:(oh-ih)/2:black,setdar=4/3",
            MediaEncoding.DvdOrDvFilter(new VideoStreamInfo(640, 480, 1, 0, 25), pal: true));
        // Cinemascope 2.39:1: 16:9 frame with bars above and below.
        Assert.Equal("scale=720:358,pad=720:480:(ow-iw)/2:(oh-ih)/2:black,setdar=16/9",
            MediaEncoding.DvdOrDvFilter(new VideoStreamInfo(1920, 804, 1, 0, 24), pal: false));
        // Portrait phone video (landscape pixels + 90° rotation): 4:3 frame with bars left and right.
        Assert.Equal("scale=304:480,pad=720:480:(ow-iw)/2:(oh-ih)/2:black,setdar=4/3",
            MediaEncoding.DvdOrDvFilter(new VideoStreamInfo(1920, 1080, 1, -90, 30), pal: false));

        Assert.True(MediaEncoding.IsPal(25));
        Assert.True(MediaEncoding.IsPal(50));
        Assert.False(MediaEncoding.IsPal(29.97));
        Assert.False(MediaEncoding.IsPal(0));
    }

    [Theory]
    [InlineData(29.97003, "30000/1001", "30000/1001")]
    [InlineData(25, "25", "25")]
    [InlineData(29.87, "30", "30000/1001")]
    [InlineData(15, "15", "24000/1001")]
    [InlineData(0, null, "25")]
    public void Frame_rates_are_made_encodable(double fps, string? nearest, string broadcast)
    {
        Assert.Equal(nearest, MediaEncoding.NearestRate(fps));
        Assert.Equal(broadcast, MediaEncoding.BroadcastRate(fps));
    }

    [Fact]
    public void Gif_uses_a_palette_pass_and_limits_size()
    {
        var passes = MediaEncoding.Plan("in.mp4", "out.gif", "gif", new MediaOptions { MaxHeight = 200 },
            new MediaInfo(TimeSpan.FromSeconds(3), Hd, null, null), "work");
        Assert.Equal(2, passes.Count);
        Assert.Equal(1, passes.Sum(p => p.Weight), 6);
        var first = passes[0].Arguments;
        var palette = After(first, "image2");
        Assert.StartsWith(Path.Combine("work", "palette-"), palette);
        Assert.Contains("palettegen", After(first, "-filter_complex"));
        var second = passes[1].Arguments;
        Assert.Equal(palette, second[second.ToList().LastIndexOf("-i") + 1]);
        Assert.Contains("fps=12,scale=w='min(iw,480)':h='min(ih,200)'", After(second, "-filter_complex"));
        Assert.Contains("paletteuse", After(second, "-filter_complex"));
    }

    [Fact]
    public void Missing_streams_are_reported_clearly()
    {
        var silent = new MediaInfo(TimeSpan.FromSeconds(1), Hd, null, null);
        var noVideo = new MediaInfo(TimeSpan.FromSeconds(1), null, new AudioStreamInfo(2, 48000), null);
        Assert.Equal("The file has no audio track.", Assert.Throws<InvalidOperationException>(() => Args("mp3", info: silent)).Message);
        Assert.Equal("The file has no video stream.", Assert.Throws<InvalidOperationException>(() => Args("mp4", info: noVideo)).Message);
        // Video without sound converts to video without an audio track.
        Assert.Contains("-an", Args("mkv", info: silent));
    }

    [Fact]
    public void Probe_output_is_parsed()
    {
        const string json = """
            {
              "streams": [
                { "index": 0, "codec_name": "h264", "codec_type": "video", "width": 1920, "height": 1080,
                  "sample_aspect_ratio": "1:1", "r_frame_rate": "30/1", "avg_frame_rate": "30000/1001",
                  "disposition": { "attached_pic": 0 }, "side_data_list": [ { "side_data_type": "Display Matrix", "rotation": -90 } ] },
                { "index": 1, "codec_name": "aac", "codec_type": "audio", "channels": 2, "sample_rate": "48000", "duration": "12.5" },
                { "index": 2, "codec_name": "mjpeg", "codec_type": "video", "width": 300, "height": 300,
                  "disposition": { "attached_pic": 1 } }
              ],
              "format": { "duration": "12.480000" }
            }
            """;
        var info = MediaInfo.Parse(json);
        Assert.Equal(12.48, info.Duration!.Value.TotalSeconds, 3);
        Assert.Equal(new VideoStreamInfo(1920, 1080, 1, -90, 30000 / 1001.0), info.Video);
        Assert.Equal(9 / 16.0, info.Video!.DisplayAspect, 3);
        Assert.Equal(new AudioStreamInfo(2, 48000), info.Audio);
        Assert.Equal(2, info.CoverStreamIndex);

        var raw = MediaInfo.Parse("""{ "streams": [ { "index": 0, "codec_type": "audio", "channels": 1, "sample_rate": "8000" } ], "format": {} }""");
        Assert.Null(raw.Duration);
        Assert.Null(raw.Video);
    }

    [Fact]
    public void Ffmpeg_progress_and_errors_are_read()
    {
        Assert.Equal(2.5, FfmpegRunner.ParsePosition("out_time_us=2500000"));
        Assert.Null(FfmpegRunner.ParsePosition("out_time_us=N/A"));
        Assert.Equal(1.25, FfmpegRunner.ParsePosition("frame_time=1.25"));
        Assert.Null(FfmpegRunner.ParsePosition("progress=continue"));
        Assert.Equal("too many channels: got 6, need 2 or fewer Error while opening encoder",
            FfmpegRunner.Summarize("[wmav2 @ 000001e0] too many channels: got 6, need 2 or fewer\r\n" +
                                   "[aost#0:1/wmav2 @ 000001e0] [enc:wmav2 @ 000001e0] Error while opening encoder\r\n"));
    }

    // ───────────────────────── Real conversions ─────────────────────────

    /// <summary>Writes a test clip with FFmpeg: moving test pattern (+ a 440 Hz tone unless <paramref name="audio"/> is false).</summary>
    private static async Task<string> MakeClipAsync(string folder, string name, double seconds = 2, string size = "320x240", int fps = 25,
        bool audio = true, int channels = 2, params string[] extra)
    {
        var path = Path.Combine(folder, name);
        List<string> args =
        [
            "-hide_banner", "-nostdin", "-v", "error", "-y",
            "-f", "lavfi", "-i", $"testsrc2=size={size}:rate={fps}:duration={seconds.ToString(CultureInfo.InvariantCulture)}",
        ];
        if (audio)
            args.AddRange(["-f", "lavfi", "-i", $"sine=frequency=440:sample_rate=44100:duration={seconds.ToString(CultureInfo.InvariantCulture)}",
                           "-ac", channels.ToString(CultureInfo.InvariantCulture)]);
        args.AddRange(extra);
        args.Add(path);
        await RunAsync(Tools!.Value.Ffmpeg, args);
        return path;
    }

    /// <summary>A WAV tone (44.1 kHz stereo).</summary>
    private static async Task<string> MakeToneAsync(string folder, string name, double seconds = 2)
    {
        var path = Path.Combine(folder, name);
        await RunAsync(Tools!.Value.Ffmpeg, ["-hide_banner", "-nostdin", "-v", "error", "-y", "-f", "lavfi",
            "-i", $"sine=frequency=440:sample_rate=44100:duration={seconds.ToString(CultureInfo.InvariantCulture)}", "-ac", "2", path]);
        return path;
    }

    private static async Task RunAsync(string exe, IEnumerable<string> args)
    {
        var result = await ProcessRunner.RunAsync(exe, args, TimeSpan.FromMinutes(2), CancellationToken.None);
        Assert.True(result.ExitCode == 0, result.StandardError);
    }

    /// <summary>What ffprobe sees in a file.</summary>
    private sealed record Probed(double Duration, List<Track> Streams)
    {
        public Track? Video => Streams.FirstOrDefault(s => s.Type == "video" && !s.Cover);
        public Track? Audio => Streams.FirstOrDefault(s => s.Type == "audio");
    }

    private sealed record Track(string Type, string Codec, int Width, int Height, int Channels, int SampleRate, long BitRate, bool Cover, int Frames);

    private static async Task<Probed> ProbeAsync(string path)
    {
        var result = await ProcessRunner.RunAsync(Tools!.Value.Ffprobe,
            ["-v", "error", "-count_frames", "-print_format", "json", "-show_format", "-show_streams", path],
            TimeSpan.FromMinutes(1), CancellationToken.None);
        Assert.True(result.ExitCode == 0, $"ffprobe {path}: {result.StandardError}");
        using var json = JsonDocument.Parse(result.StandardOutput);
        static string S(JsonElement e, string name) => e.TryGetProperty(name, out var v) ? v.ToString() : "";
        static long N(JsonElement e, string name) => long.TryParse(S(e, name), out var n) ? n : 0;
        var streams = json.RootElement.GetProperty("streams").EnumerateArray().Select(s => new Track(
            S(s, "codec_type"), S(s, "codec_name"), (int)N(s, "width"), (int)N(s, "height"), (int)N(s, "channels"),
            (int)N(s, "sample_rate"), N(s, "bit_rate"),
            s.TryGetProperty("disposition", out var d) && d.TryGetProperty("attached_pic", out var a) && a.GetInt32() == 1,
            (int)N(s, "nb_read_frames"))).ToList();
        var duration = double.TryParse(S(json.RootElement.GetProperty("format"), "duration"), NumberStyles.Float, CultureInfo.InvariantCulture, out var d2) ? d2 : 0;
        return new Probed(duration, streams);
    }

    private async Task<string> ConvertAsync(string input, string target, MediaOptions? media = null)
    {
        var preset = new Preset { TargetFormat = target, Media = media ?? new MediaOptions() };
        var job = await fx.ConvertAsync([input], preset);
        Assert.True(job.State == JobState.Completed, string.Join("; ", job.Files.Select(f => $"{f.ErrorKey} {f.ErrorDetail}")));
        var output = Assert.Single(job.Outputs);
        Assert.Equal("." + FormatRegistry.Get(target).PrimaryExtension, Path.GetExtension(output));
        return output;
    }

    /// <summary>ffprobe's codec name for each encoder Filee uses.</summary>
    private static string Decoded(string encoder) => encoder switch
    {
        "libx264" => "h264",
        "libvpx-vp9" => "vp9",
        "libtheora" => "theora",
        "libopus" => "opus",
        "libmp3lame" => "mp3",
        "libvorbis" => "vorbis",
        "libopencore_amrnb" => "amr_nb",
        _ => encoder,
    };

    [Theory]
    [InlineData("webm")]
    [InlineData("mov")]
    [InlineData("mkv")]
    [InlineData("avi")]
    public async Task Mp4_converts_to_other_video_formats(string target)
    {
        SkipUnlessInstalled();
        var source = await MakeClipAsync(fx.NewFolder(), "clip.mp4");
        var probed = await ProbeAsync(await ConvertAsync(source, target));

        var spec = MediaEncoding.VideoTargets[target];
        Assert.Equal(Decoded(spec.VideoCodec!), probed.Video?.Codec);
        Assert.Equal(Decoded(spec.AudioCodec), probed.Audio?.Codec);
        Assert.Equal((320, 240), (probed.Video!.Width, probed.Video.Height));
        Assert.InRange(probed.Duration, 1.7, 2.4);
    }

    [Fact]
    public async Task Every_target_format_is_written_with_the_planned_codecs()
    {
        SkipUnlessInstalled();
        var folder = fx.NewFolder();
        var source = await MakeClipAsync(folder, "all.mp4", seconds: 1, size: "160x120");
        var failures = new System.Collections.Concurrent.ConcurrentBag<string>();
        var targets = MediaEncoding.VideoTargets.Concat(MediaEncoding.AudioTargets).ToList();
        await Parallel.ForEachAsync(targets, new ParallelOptions { MaxDegreeOfParallelism = 3 }, async (entry, _) =>
        {
            var (target, spec) = entry;
            try
            {
                var probed = await ProbeAsync(await ConvertAsync(source, target));
                if (spec.VideoCodec is not null && probed.Video?.Codec != Decoded(spec.VideoCodec))
                    failures.Add($"{target}: video {probed.Video?.Codec}");
                if (spec.VideoCodec is null && probed.Video is not null)
                    failures.Add($"{target}: unexpected video stream");
                if (probed.Audio?.Codec != Decoded(spec.AudioCodec))
                    failures.Add($"{target}: audio {probed.Audio?.Codec}");
                if (probed.Duration is < 0.7 or > 1.5)
                    failures.Add($"{target}: duration {probed.Duration}");
                if (target is "vob" or "dv" && probed.Video is { } frame && (frame.Width, frame.Height) != (720, 576)) // 25 fps source = PAL
                    failures.Add($"{target}: frame {frame.Width}×{frame.Height}");
            }
            catch (Exception ex)
            {
                failures.Add($"{target}: {ex.Message}");
            }
        });
        Assert.Empty(failures);
    }

    [Fact]
    public async Task Video_becomes_an_animated_gif_and_back()
    {
        SkipUnlessInstalled();
        var source = await MakeClipAsync(fx.NewFolder(), "anim.mp4", size: "640x360");
        var gif = await ConvertAsync(source, "gif");
        var probed = await ProbeAsync(gif);
        Assert.Equal("gif", probed.Video?.Codec);
        Assert.Equal((480, 270), (probed.Video!.Width, probed.Video.Height)); // Balanced: at most 480 px wide
        Assert.InRange(probed.Video.Frames, 20, 30); // 2 s at 12 fps
        Assert.Null(probed.Audio);

        // GIF → MP4.
        var mp4 = await ProbeAsync(await ConvertAsync(gif, "mp4"));
        Assert.Equal("h264", mp4.Video?.Codec);
        Assert.Equal((480, 270), (mp4.Video!.Width, mp4.Video.Height));
        Assert.InRange(mp4.Duration, 1.5, 2.5);
    }

    [Fact]
    public async Task Video_gives_a_still_frame_for_images()
    {
        SkipUnlessInstalled();
        var folder = fx.NewFolder();
        // Anamorphic 4:3 DV-style video: 720×480 pixels that are shown narrower than they are stored.
        var source = await MakeClipAsync(folder, "still.mkv", seconds: 3, size: "720x480", extra: ["-vf", "setsar=8/9"]);

        var png = await ProbeAsync(await ConvertAsync(source, "png"));
        Assert.Equal("png", png.Video?.Codec);
        Assert.Equal((640, 480), (png.Video!.Width, png.Video.Height)); // square pixels

        var jpg = await ConvertAsync(source, "jpg");
        using var image = new ImageMagick.MagickImage(jpg);
        Assert.Equal((640u, 480u), (image.Width, image.Height));
    }

    [Fact]
    public async Task Odd_sized_surround_video_is_encoded_everywhere()
    {
        SkipUnlessInstalled();
        // 321×241 at 15 fps with 6 channels: odd sizes, a rate MPEG-2 cannot store and more channels than WMA/MP3 hold.
        var source = await MakeClipAsync(fx.NewFolder(), "odd.mkv", size: "320x240", fps: 15, channels: 6,
            extra: ["-vf", "pad=321:241", "-c:v", "libx264", "-pix_fmt", "yuv444p", "-c:a", "aac"]);
        foreach (var target in new[] { "mp4", "wmv", "mpg", "avi", "wma", "mp3" })
        {
            var probed = await ProbeAsync(await ConvertAsync(source, target));
            Assert.NotNull(probed.Audio);
            if (probed.Video is { } video)
                Assert.Equal((320, 240), (video.Width, video.Height));
        }
    }

    [Theory]
    [InlineData("mp3", "mp3")]
    [InlineData("flac", "flac")]
    [InlineData("ogg", "vorbis")]
    [InlineData("opus", "opus")]
    [InlineData("m4a", "aac")]
    public async Task Wav_converts_to_audio_formats(string target, string codec)
    {
        SkipUnlessInstalled();
        var source = await MakeToneAsync(fx.NewFolder(), "tone.wav");
        var probed = await ProbeAsync(await ConvertAsync(source, target));
        Assert.Equal(codec, probed.Audio?.Codec);
        Assert.Equal(2, probed.Audio!.Channels);
        Assert.Null(probed.Video);
        Assert.InRange(probed.Duration, 1.8, 2.3);
    }

    [Fact]
    public async Task Audio_is_extracted_from_video()
    {
        SkipUnlessInstalled();
        var source = await MakeClipAsync(fx.NewFolder(), "talk.mp4");
        var probed = await ProbeAsync(await ConvertAsync(source, "mp3"));
        Assert.Equal("mp3", Assert.Single(probed.Streams).Codec);
        Assert.InRange(probed.Duration, 1.8, 2.3);
    }

    [Fact]
    public async Task Max_height_scales_down_only()
    {
        SkipUnlessInstalled();
        var folder = fx.NewFolder();
        var hd = await MakeClipAsync(folder, "hd.mp4", seconds: 1, size: "1920x1080", audio: false);
        var probed = await ProbeAsync(await ConvertAsync(hd, "mp4", new MediaOptions { MaxHeight = 720 }));
        Assert.Equal((1280, 720), (probed.Video!.Width, probed.Video.Height));

        var small = await MakeClipAsync(folder, "small.mp4", seconds: 1, size: "320x240", audio: false);
        probed = await ProbeAsync(await ConvertAsync(small, "mp4", new MediaOptions { MaxHeight = 720 }));
        Assert.Equal((320, 240), (probed.Video!.Width, probed.Video.Height));
    }

    [Fact]
    public async Task Portrait_phone_video_is_rotated_upright()
    {
        SkipUnlessInstalled();
        var folder = fx.NewFolder();
        var landscape = await MakeClipAsync(folder, "landscape.mp4", seconds: 1, size: "640x360");
        // Like a phone: landscape pixels plus a display matrix that turns them by 90°.
        var phone = Path.Combine(folder, "phone.mp4");
        await RunAsync(Tools!.Value.Ffmpeg, ["-hide_banner", "-nostdin", "-v", "error", "-y", "-display_rotation", "90", "-i", landscape, "-c", "copy", phone]);

        var probed = await ProbeAsync(await ConvertAsync(phone, "webm", new MediaOptions { MaxHeight = 320 }));
        Assert.Equal((180, 320), (probed.Video!.Width, probed.Video.Height));
    }

    [Fact]
    public async Task Remove_audio_and_audio_bitrate_options_apply()
    {
        SkipUnlessInstalled();
        var folder = fx.NewFolder();
        var source = await MakeClipAsync(folder, "options.mp4");

        var muted = await ProbeAsync(await ConvertAsync(source, "mp4", new MediaOptions { RemoveAudio = true }));
        Assert.NotNull(muted.Video);
        Assert.Null(muted.Audio);

        var tone = await MakeToneAsync(folder, "bitrate.wav");
        var mp3 = await ProbeAsync(await ConvertAsync(tone, "mp3", new MediaOptions { AudioBitrateKbps = 128 }));
        Assert.Equal(128_000, mp3.Audio!.BitRate);
        var m4a = await ProbeAsync(await ConvertAsync(tone, "m4a", new MediaOptions { AudioBitrateKbps = 96 }));
        Assert.InRange(m4a.Audio!.BitRate, 70_000, 110_000);
    }

    [Fact]
    public async Task Video_without_sound_converts_but_has_no_audio_to_extract()
    {
        SkipUnlessInstalled();
        var source = await MakeClipAsync(fx.NewFolder(), "silent.mp4", audio: false);
        var probed = await ProbeAsync(await ConvertAsync(source, "webm"));
        Assert.Equal("vp9", probed.Video?.Codec);
        Assert.Null(probed.Audio);

        var job = await fx.ConvertAsync([source], new Preset { TargetFormat = "mp3" });
        var file = Assert.Single(job.Files);
        Assert.Equal(FileState.Failed, file.State);
        Assert.Contains("no audio track", file.ErrorDetail);
        Assert.Empty(Directory.GetFiles(Path.GetDirectoryName(source)!, "*.mp3"));
    }

    [Fact]
    public async Task Cover_art_and_tags_are_kept()
    {
        SkipUnlessInstalled();
        var folder = fx.NewFolder();
        var cover = Path.Combine(folder, "cover.png");
        await RunAsync(Tools!.Value.Ffmpeg, ["-hide_banner", "-nostdin", "-v", "error", "-y", "-f", "lavfi", "-i", "testsrc2=size=200x200", "-frames:v", "1", cover]);
        var song = Path.Combine(folder, "song.mp3");
        await RunAsync(Tools.Value.Ffmpeg, ["-hide_banner", "-nostdin", "-v", "error", "-y", "-f", "lavfi", "-i", "sine=duration=2", "-i", cover,
            "-map", "0:a", "-map", "1:v", "-c:v", "copy", "-disposition:v:0", "attached_pic", "-metadata", "title=노래 제목", song]);

        foreach (var target in new[] { "flac", "m4a" })
        {
            var output = await ConvertAsync(song, target);
            var probed = await ProbeAsync(output);
            Assert.Contains(probed.Streams, s => s.Cover && s.Codec == "png");
            var tags = await ProcessRunner.RunAsync(Tools.Value.Ffprobe, ["-v", "error", "-show_entries", "format_tags=title,major_brand", "-of", "json", output],
                TimeSpan.FromMinutes(1), CancellationToken.None);
            Assert.Contains("노래 제목", tags.StandardOutput);
        }
    }

    // ───────────────────────── Progress and cancellation ─────────────────────────

    private sealed class FolderAllocator(string folder) : IOutputAllocator
    {
        public List<string> Allocated { get; } = [];

        public string? Allocate(string extension, string? suffix = null)
        {
            var path = Path.Combine(folder, $"out{suffix}.{extension}");
            Allocated.Add(path);
            return path;
        }
    }

    /// <summary>Records every reported value synchronously (Progress&lt;T&gt; would post to the thread pool).</summary>
    private sealed class Recorder(Action<double>? onReport = null) : IProgress<double>
    {
        public List<double> Values { get; } = [];

        public void Report(double value)
        {
            lock (Values)
                Values.Add(value);
            onReport?.Invoke(value);
        }
    }

    private static ConversionStep Step(string input, string from, string to, string folder, MediaOptions? media = null) =>
        new(input, from, to, new Preset { TargetFormat = to, Media = media ?? new MediaOptions() }, new FolderAllocator(folder), folder);

    [Fact]
    public async Task Progress_rises_while_ffmpeg_works()
    {
        SkipUnlessInstalled();
        var folder = fx.NewFolder();
        // Long enough for several of FFmpeg's half-second progress reports.
        var source = await MakeClipAsync(folder, "long.mp4", seconds: 40, size: "640x360", extra: ["-c:v", "libx264", "-preset", "ultrafast"]);
        var converter = new FfmpegConverter();
        Assert.True(converter.GetStatus().IsAvailable);

        var recorder = new Recorder();
        var outputs = await converter.ConvertAsync(Step(source, "mp4", "mkv", folder, new MediaOptions { Quality = MediaQuality.High }), recorder, CancellationToken.None);

        Assert.True(File.Exists(Assert.Single(outputs)));
        var values = recorder.Values.ToList();
        Assert.Equal(1, values[^1]);
        Assert.True(values.Zip(values.Skip(1)).All(p => p.First <= p.Second), string.Join(", ", values));
        Assert.True(values.Count(v => v is > 0.02 and < 1) >= 3, string.Join(", ", values));
    }

    [Fact]
    public async Task Gif_palette_pass_reports_progress_too()
    {
        SkipUnlessInstalled();
        var folder = fx.NewFolder();
        var source = await MakeClipAsync(folder, "gifprogress.mp4", seconds: 30, size: "640x360", audio: false, extra: ["-c:v", "libx264", "-preset", "ultrafast"]);
        var recorder = new Recorder();
        var converter = new FfmpegConverter();
        converter.GetStatus();
        await converter.ConvertAsync(Step(source, "mp4", "gif", folder, new MediaOptions { Quality = MediaQuality.Small }), recorder, CancellationToken.None);
        // The palette pass covers the first 40 %: values inside it prove its progress is read.
        Assert.Contains(recorder.Values, v => v is > 0.05 and < 0.4);
    }

    [Fact]
    public async Task Cancelling_kills_ffmpeg_and_removes_the_partial_output()
    {
        SkipUnlessInstalled();
        var folder = fx.NewFolder();
        var source = await MakeClipAsync(folder, "cancel.mp4", seconds: 60, size: "1280x720", extra: ["-c:v", "libx264", "-preset", "ultrafast"]);
        using var cancellation = new CancellationTokenSource();
        var recorder = new Recorder(v =>
        {
            if (v > 0.05)
                cancellation.Cancel();
        });
        var converter = new FfmpegConverter();
        converter.GetStatus();
        var step = Step(source, "mp4", "webm", folder, new MediaOptions { Quality = MediaQuality.High });
        cancellation.CancelAfter(TimeSpan.FromSeconds(30)); // in case no progress arrives at all
        var watch = Stopwatch.StartNew();

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => converter.ConvertAsync(step, recorder, cancellation.Token));

        Assert.True(watch.Elapsed < TimeSpan.FromSeconds(60), "VP9 encoding of the whole clip should not have finished");
        var output = Assert.Single(((FolderAllocator)step.Output).Allocated);
        Assert.False(File.Exists(output));
        // No FFmpeg of ours is left running (it would keep the CPU busy and the output locked).
        var deadline = Stopwatch.StartNew();
        while (RunningFfmpeg(Tools!.Value.Ffmpeg) && deadline.Elapsed < TimeSpan.FromSeconds(10))
            await Task.Delay(200, TestContext.Current.CancellationToken);
        Assert.False(RunningFfmpeg(Tools.Value.Ffmpeg));
    }

    /// <summary>
    /// True if a process started from <paramref name="exe"/> is running (tests of this class run one at a time, so
    /// it can only be the one that should have been killed).
    /// </summary>
    private static bool RunningFfmpeg(string exe)
    {
        foreach (var process in Process.GetProcessesByName(Path.GetFileNameWithoutExtension(exe)))
        {
            using (process)
            {
                try
                {
                    if (!process.HasExited && string.Equals(process.MainModule?.FileName, exe, StringComparison.OrdinalIgnoreCase))
                        return true;
                }
                catch (Exception ex) when (ex is InvalidOperationException or System.ComponentModel.Win32Exception)
                {
                    // Exited meanwhile or belongs to another user: not ours.
                }
            }
        }
        return false;
    }
}
